stages:
  - deploy_staging
  - deploy_production

image: docker:24.0.5
services:
  - docker:24.0.5-dind

variables:
  DOCKER_IMAGE: demo1
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_VERIFY: "1"
  DOCKER_CERT_PATH: "/certs/client"

build:
  stage: build
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
  script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - docker build -t $DOCKER_IMAGE:latest .
    - docker push $DOCKER_IMAGE:latest
  needs:
    - test
  only:
    - master
    - develop

deploy_staging:
  stage: deploy_staging
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
    - kubectl config get-contexts
    - kubectl config use-context zagbor/demo1:myagent
    - kubectl apply -f k8s/staging/
  environment:
    name: staging
  needs:
    - build
  only:
    - develop

deploy_production:
  stage: deploy_production
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  before_script:
  script:
    - kubectl config get-contexts
    - kubectl config use-context zagbor/demo1:myagent
    - kubectl apply -f k8s/production/
  environment:
    name: production
  needs:
    - build
  only:
    - master