apiVersion: v1
kind: Service
metadata:
  name: demo1-staging-service
spec:
  selector:
    app: demo1
    environment: staging
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
