apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo1-production
  labels:
    app: demo1
    environment: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo1
      environment: production
  template:
    metadata:
      labels:
        app: demo1
        environment: production
    spec:
      containers:
        - name: demo1
          image: zagbor/demo1:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-production-config